# Analyzing our Planet Earth data

Let's use Python to input and analyze the data we collected in the Hall of Planet Earth.

**Reminder: To run the code in a Jupyter Notebook cell, click inside the cell and press "shift" and "return" on your keyboard at the same time.**

## Working with numerical earth science data

Assign the percent of each ore that contains the mineral to each variable below:

In [52]:
# Note: You do not need to include the % sign. 
chromium = 25
vanadium = 2
platinum = 0.0008

Now print out each of these variables:

In [53]:
print(chromium)
print(vanadium)
print(platinum)

25
2
0.0008

Next, assign the percent of vanadium ore that **does not** contain the mineral to a new variable and then print it out:

In [54]:
emptyOre = (100 - vanadium)
print(emptyOre)# Hint: You will need to use subtraction

98

Now convert the value you calculated above into a decimal and print the result:

In [55]:
print(emptyOre / 100)# Hint: You will need to use division

0.98

Can you identify which of the values you worked with above are integers and which are floats?

## Working with textual earth science data

Assign the name of each type of lava to a variable below:

In [56]:
lavatype_1 = " pahoehoe"
lavatype_2 = " aa" # Hint: Remember that strings need to be in quotes!

Now print out each of these variables:

In [57]:
print(lavatype_1 + lavatype_2)

 pahoehoe aa

You can add strings together to make one long print statement, even if some of those strings are stored in variables. 

Assign your favorite object from the Hall of Planet Earth as a string to the object variable below and then run the cell below to see how it works:

In [72]:
name = "petrified tree "
print("The " + name + "is one of the exhibited objects that helps us learn about planet Earth!")

The petrified tree is one of the exhibited objects that helps us learn about planet Earth!

Now try printing out a sentence that tells the reader what the two types of lava are:

In [59]:
print("The two types of lava are" + lavatype_1 + " and" + lavatype_2 + ".")

The two types of lava are pahoehoe and aa.

## Mixing different types of earth science data

Create a variable for each piece of data related to the deformed rocks from Wingdale, NY and decide whether the value should be a string, a float, or an integer:
- Where the rock was found
- Type of rock
- Rock age
- Temperature at which the rock formed
- Depth at which the rock formed

In [60]:
location = "Wingdale, NY"
rock_type = "schists"
rock_age = 440000000
formation_temp = 550
formation_depth = 8 #I did not have the data for this

Print out a sentence that explains where the rocks were found and what kind of rock they are:

In [61]:
print("The rocks are found " + location + " and are " + rock_type + ".")

The rocks are found Wingdale, NY and are schists.

Print out the difference between the deformed rock's temperature at formation and the boiling point of water (100 degrees Celsius):

In [62]:
print(formation_temp - 100)

450

Create two new variables that contain the age and length of the San Andreas Fault:

In [63]:
faultAge = 30000000
faultDepth = 1200

Print out the difference in age between the deformed rocks and the San Andreas Fault:

In [64]:
print(rock_age-faultAge)

410000000

How much longer is the San Andreas Fault than the depth of the deformed rock's formation? Print out the difference:

In [65]:
print(faultDepth-formation_depth)

1192

## Bonus Challenge 1
If you finish everything above, try this bonus challenge

Create three new variables with information from your data collection sheet and experiment with adding, subtracting, and printing these variables:

In [66]:
averageMovement=5
faultAge = 30000000
faultDepth = 1200
distanceMoved=300
year=365
total=distanceMoved/faultAge*year
print(total)

# Hint: Think about which data types can be added together

0.0036500000000000005

## Bonus Challenge 2
If you finish everything above, try this bonus challenge

Run the code below to learn about the type() function:

In [67]:
var1 = 5
var2 = "Rocks rock"
var3 = 3.2

#The type() function tells you the data type of a value
print(type(var1))
print(type(var2))
print(type(var3))

<class 'int'>
<class 'str'>
<class 'float'>

Now try it yourself! print out the type of some variables you've created above:

In [68]:
print(type (rock_type))
print(type (rock_age))
print(type (location))
print( type (formation_temp))

<class 'str'>
<class 'int'>
<class 'str'>
<class 'int'>

You can also change the type of some values stored in variables using the following functions:
- str() turns a value into a string
- int() turns a value into an integer
- float() turns a value into a float

Run the code below to learn more:

In [69]:
varA = "1"
varB = 1.0
varC = 1

print(int(varA))
print(str(varB))
print(float(varC))

1
1.0
1.0

Not all values can be turned into all types. Try running the code below:

In [70]:
print(int("Rocks rock!"))

ValueError: ignored

Now try it yourself! Create your own variables and try changing their types:

In [71]:
print(str (42.0))
print(int (-.277777777))
print(float (7679321))
print(str (45/8 + -.4444444 ))
print(int (2/3))
print(float (10/10))
print(int (22/7))
print(float (22/7))

42.0
0
7679321.0
5.1805556
0
1.0
3
3.142857142857143